version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: TaskManagement
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6380:6379"

  api:
    build:
      context: .
      dockerfile: TaskManagement.API/dockerfile
    container_name: api
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__TaskManagementConnection=Server=mysql;Database=TaskManagement;User=root;Password=root;
      - Redis__ConnectionString=redis:6379
    ports:
      - "5000:8080"

volumes:
  mysql-data: