name: CI/CD Pipeline
on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
      
      # 2. Setup .NET environment
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      
      # 3. Restore dependencies
      - name: Restore dependencies
        run: dotnet restore
      
      # 4. Build the solution
      - name: Build solution
        run: dotnet build --configuration Release --no-restore
      
      # 5. Run tests
      - name: Run tests
        run: dotnet test --no-build --verbosity normal
  
  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
      
      # 2. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      # 3. Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # 4. Build and push Docker image
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./TaskManagement.API/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.DOCKER_USERNAME }}/taskmanagement-api:latest,${{ secrets.DOCKER_USERNAME }}/taskmanagement-api:${{ github.sha }}
